# Generated by the audible-rs release workflow — do not edit by hand.
# Version and checksums are rewritten on every release; a hand edit is lost
# with the next one.
class AudibleRs < Formula
  desc "Command-line client for your Audible library"
  homepage "https://github.com/mkb79/audible-rs"
  license "MIT"

  # Prebuilt release binaries, verified against the release's SHA256SUMS.
  # Nothing is compiled here: the project already publishes one archive per
  # target, and building from source would need a C toolchain for the bundled
  # SQLite for no gain.
  on_macos do
    on_arm do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.5/audible-0.1.0-alpha.5-aarch64-apple-darwin.tar.gz"
      sha256 "182c7788ba7e720a5df9cc8925da722e3b0adf85e1fb7aadbecc6ad9de41dd35"
    end
    on_intel do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.5/audible-0.1.0-alpha.5-x86_64-apple-darwin.tar.gz"
      sha256 "0b38dc3ab9a5af05ec7a9767590cce3c01e8909b65cf8c20ec63af5f83a280dd"
    end
  end

  # The Linux binaries are statically linked against musl, so they do not
  # depend on the host's glibc.
  on_linux do
    on_arm do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.5/audible-0.1.0-alpha.5-aarch64-unknown-linux-musl.tar.gz"
      sha256 "f3d2f7f6f03260d4a333a68ffa429dcd49a958815fc23185e253af0047a098f1"
    end
    on_intel do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.5/audible-0.1.0-alpha.5-x86_64-unknown-linux-musl.tar.gz"
      sha256 "ae01391f21002faa78495bb5d20fb8398062a6ed593107f6728ec89f210eaaf0"
    end
  end

  def install
    bin.install "audible"

    # `audible completions <shell>` takes the shell positionally and prints to
    # stdout — which is the default parameter format here (do not pass
    # shell_parameter_format, that would send `--shell=bash`).
    generate_completions_from_executable(bin/"audible", "completions", base_name: "audible")
  end

  test do
    # Exact, not a substring: a release binary reports a bare version. One
    # built from source appends its commit (`0.1.0-alpha.5+g1a2b3c4`), which
    # would mean the release pipeline shipped the wrong thing.
    assert_equal "audible #{version}", shell_output("#{bin}/audible --version").strip

    # The binary runs and its help is intact.
    assert_match "Access your Audible library", shell_output("#{bin}/audible --help")

    # No account is configured in the test sandbox, so a command that needs
    # one must fail cleanly rather than crash.
    assert_match(/account|config/i, shell_output("#{bin}/audible library list 2>&1", 1))
  end
end
