# Generated by the audible-rs release workflow — do not edit by hand.
# Version and checksums are rewritten on every release; a hand edit is lost
# with the next one.
class AudibleRs < Formula
  desc "Command-line client for your Audible library"
  homepage "https://github.com/mkb79/audible-rs"
  license "MIT"

  # Prebuilt release binaries, verified against the release's SHA256SUMS.
  # Nothing is compiled here: the project already publishes one archive per
  # target, and building from source would need a C toolchain for the bundled
  # SQLite for no gain.
  on_macos do
    on_arm do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.7/audible-0.1.0-alpha.7-aarch64-apple-darwin.tar.gz"
      sha256 "0127d38bd2a6a038bd51a0ef37a24df8af68afb07b1545630b52e7ca69ce5512"
    end
    on_intel do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.7/audible-0.1.0-alpha.7-x86_64-apple-darwin.tar.gz"
      sha256 "545f99766aa821c1aa4ac9fc5b77463ee8445b652dd7503d941fa7cc5460bb1a"
    end
  end

  # The Linux binaries are statically linked against musl, so they do not
  # depend on the host's glibc.
  on_linux do
    on_arm do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.7/audible-0.1.0-alpha.7-aarch64-unknown-linux-musl.tar.gz"
      sha256 "9d32e3cd866a49493d1832d05730b0a0c874137c709cc5e61e85e3cc3f12c04d"
    end
    on_intel do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.7/audible-0.1.0-alpha.7-x86_64-unknown-linux-musl.tar.gz"
      sha256 "99bc77a177d59ef38077a2459cd3dc720d359a488383ddbb540772fefb1e1502"
    end
  end

  def install
    bin.install "audible"

    # `audible completions <shell>` takes the shell positionally and prints to
    # stdout — which is the default parameter format here (do not pass
    # shell_parameter_format, that would send `--shell=bash`).
    generate_completions_from_executable(bin/"audible", "completions", base_name: "audible")
  end

  test do
    # Exact, not a substring: a release binary reports a bare version. One
    # built from source appends its commit (`0.1.0-alpha.7+g1a2b3c4`), which
    # would mean the release pipeline shipped the wrong thing.
    assert_equal "audible #{version}", shell_output("#{bin}/audible --version").strip

    # The binary runs and its help is intact.
    assert_match "Access your Audible library", shell_output("#{bin}/audible --help")

    # No account is configured in the test sandbox, so a command that needs
    # one must fail cleanly rather than crash.
    assert_match(/account|config/i, shell_output("#{bin}/audible library list 2>&1", 1))
  end
end
