# Generated by the audible-rs release workflow — do not edit by hand.
# Version and checksums are rewritten on every release; a hand edit is lost
# with the next one.
class AudibleRs < Formula
  desc "Command-line client for your Audible library"
  homepage "https://github.com/mkb79/audible-rs"
  license "MIT"

  # Prebuilt release binaries, verified against the release's SHA256SUMS.
  # Nothing is compiled here: the project already publishes one archive per
  # target, and building from source would need a C toolchain for the bundled
  # SQLite for no gain.
  on_macos do
    on_arm do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.6/audible-0.1.0-alpha.6-aarch64-apple-darwin.tar.gz"
      sha256 "91f8b2ab9306f58a86f60c603ec2c0e526ef688c38ec539f636777d681f9acdb"
    end
    on_intel do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.6/audible-0.1.0-alpha.6-x86_64-apple-darwin.tar.gz"
      sha256 "fb0caaac70f10e755694043632d50863d8a8b345838742e6a729fce0aa84ec4d"
    end
  end

  # The Linux binaries are statically linked against musl, so they do not
  # depend on the host's glibc.
  on_linux do
    on_arm do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.6/audible-0.1.0-alpha.6-aarch64-unknown-linux-musl.tar.gz"
      sha256 "7d6d2998efb763eb18ea81afa62f642de8d6b5f487b567831d67c437836523ad"
    end
    on_intel do
      url "https://github.com/mkb79/audible-rs/releases/download/v0.1.0-alpha.6/audible-0.1.0-alpha.6-x86_64-unknown-linux-musl.tar.gz"
      sha256 "fbb4f0a4fec22c892b7ac73fd76d5ad8cfc6c2150e3df50ce455df4e6f449baa"
    end
  end

  def install
    bin.install "audible"

    # `audible completions <shell>` takes the shell positionally and prints to
    # stdout — which is the default parameter format here (do not pass
    # shell_parameter_format, that would send `--shell=bash`).
    generate_completions_from_executable(bin/"audible", "completions", base_name: "audible")
  end

  test do
    # Exact, not a substring: a release binary reports a bare version. One
    # built from source appends its commit (`0.1.0-alpha.6+g1a2b3c4`), which
    # would mean the release pipeline shipped the wrong thing.
    assert_equal "audible #{version}", shell_output("#{bin}/audible --version").strip

    # The binary runs and its help is intact.
    assert_match "Access your Audible library", shell_output("#{bin}/audible --help")

    # No account is configured in the test sandbox, so a command that needs
    # one must fail cleanly rather than crash.
    assert_match(/account|config/i, shell_output("#{bin}/audible library list 2>&1", 1))
  end
end
